version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - pulsedb
    depends_on:
      - pulsedb
    networks:
      - api_network
  pulsedb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data
    command: mongod --smallfiles --logpath=/dev/null --quiet
    networks:
      - api_network

networks:
  api_network:
    driver: bridge