version: "3"
services:
  pulse-migrate:
    image: gpitfutures/pulsetile_migrate
    links:
      - pulse-db
    depends_on:
      - pulse-db
    networks:
      - pulse-network
  pulse-db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data
    command: mongod --smallfiles --logpath=/dev/null --quiet
    networks:
      - pulse-network

networks:
  pulse-network:
    driver: bridge