sudo: required
dist: trusty

language: node_js

cache:
  directories:
    - node_modules

branches:
  only:
    - master

node_js:
  - 8

before_install:
- export TZ=Europe/Kiev

install:
  - npm install -g codecov
  - npm install -g webpack
  - npm install

script:
  - npm run test
  - npm run build

after_success:
  - npm run report-coverage
  - npm run semantic-release

notifications:
  email:
    recipients: tony.shannon@ripple.foundation
    on_success: always
    on_failure: always