FROM microsoft/dotnet:2.1-sdk-alpine AS build
WORKDIR /app

COPY ./Core ./Core
COPY ./Migration ./Migration
RUN dotnet restore Migration/Pulse.Migration/Pulse.Migration.csproj
RUN dotnet publish Migration/Pulse.Migration/Pulse.Migration.csproj -c Release -r linux-musl-x64 -o ../../out

FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Pulse.Migration.dll", "mongodb://pulse-db:27017"]
