FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /app

COPY . ./
RUN dotnet restore
RUN dotnet publish Migration/Pulse.Migration/Pulse.Migration.csproj -c Release -r linux-x64 -o ../../out

FROM microsoft/aspnetcore:2.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Pulse.Migration.dll", "mongodb://pulsedb:27017"]
